CAR_BRAND_MODELS = {
    'Toyota': ['Corolla', 'Camry', 'Yaris', 'Hilux', 'Land Cruiser', 'Prado', 'RAV4', 'Fortuner', 'Avalon'],
    'Nissan': ['Sunny', 'Altima', 'Maxima', 'Patrol', 'X-Trail', 'Navara', 'Kicks', 'Sentra'],
    'Honda': ['Civic', 'Accord', 'City', 'CR-V', 'Pilot', 'HR-V'],
    'Hyundai': ['Accent', 'Elantra', 'Sonata', 'Tucson', 'Santa Fe', 'Creta', 'Palisade'],
    'Kia': ['Rio', 'Cerato', 'Optima', 'Sportage', 'Sorento', 'Telluride', 'Seltos'],
    'Mazda': ['Mazda 3', 'Mazda 6', 'CX-3', 'CX-5', 'CX-9'],
    'Mitsubishi': ['Lancer', 'Attrage', 'ASX', 'Outlander', 'Pajero', 'L200'],
    'Chevrolet': ['Spark', 'Aveo', 'Malibu', 'Captiva', 'Tahoe', 'Suburban', 'Silverado'],
    'Ford': ['Figo', 'Focus', 'Fusion', 'Escape', 'Explorer', 'Expedition', 'F-150', 'Ranger'],
    'Jeep': ['Renegade', 'Compass', 'Cherokee', 'Grand Cherokee', 'Wrangler'],
    'Dodge': ['Charger', 'Challenger', 'Durango'],
    'GMC': ['Terrain', 'Acadia', 'Yukon', 'Sierra'],
    'BMW': ['116i', '320i', '330i', '520i', '730Li', 'X1', 'X3', 'X5', 'X6'],
    'Mercedes-Benz': ['A-Class', 'C-Class', 'E-Class', 'S-Class', 'GLA', 'GLC', 'GLE', 'G-Class'],
    'Audi': ['A3', 'A4', 'A6', 'A8', 'Q3', 'Q5', 'Q7', 'Q8'],
    'Lexus': ['ES', 'IS', 'LS', 'RX', 'NX', 'GX', 'LX'],
    'Infiniti': ['Q50', 'Q60', 'QX50', 'QX60', 'QX80'],
    'Volkswagen': ['Polo', 'Golf', 'Passat', 'Tiguan', 'Touareg'],
    'Skoda': ['Fabia', 'Octavia', 'Superb', 'Kodiaq', 'Karoq'],
    'Peugeot': ['208', '301', '308', '3008', '5008'],
    'Renault': ['Logan', 'Megane', 'Duster', 'Koleos'],
    'Volvo': ['S60', 'S90', 'XC40', 'XC60', 'XC90'],
    'Porsche': ['Macan', 'Cayenne', 'Panamera', '911'],
    'Land Rover': ['Discovery Sport', 'Discovery', 'Range Rover Evoque', 'Range Rover Sport', 'Range Rover'],
    'Jaguar': ['XE', 'XF', 'F-Pace', 'E-Pace'],
    'Tesla': ['Model 3', 'Model S', 'Model X', 'Model Y'],
    'Suzuki': ['Swift', 'Dzire', 'Baleno', 'Vitara', 'Jimny'],
    'Isuzu': ['D-Max', 'MU-X'],
    'MG': ['MG5', 'MG6', 'ZS', 'HS', 'RX8'],
    'Geely': ['Emgrand', 'Coolray', 'Tugella', 'Azkarra'],
    'Chery': ['Arrizo 5', 'Tiggo 2', 'Tiggo 7', 'Tiggo 8'],
    'Haval': ['H6', 'H9', 'Jolion'],
}
