# Generated by Django 5.2.4 on 2026-02-28 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50, verbose_name='الماركة')),
                ('model_name', models.CharField(max_length=50, verbose_name='الموديل')),
                ('vin', models.CharField(max_length=17, unique=True, verbose_name='رقم الشاسيه')),
                ('year', models.PositiveIntegerField(verbose_name='سنة الصنع')),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر التكلفة')),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر البيع')),
                ('is_sold', models.BooleanField(default=False, verbose_name='تم البيع؟')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم العميل')),
                ('phone', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('national_id', models.CharField(max_length=20, unique=True, verbose_name='رقم الهوية')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر البيع النهائي')),
                ('sale_date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ البيع')),
                ('car', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sales.car', verbose_name='السيارة')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.customer', verbose_name='العميل')),
            ],
        ),
    ]
