# Generated by Django 5.2.4 on 2026-02-28 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_alter_notification_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='currency',
            field=models.CharField(choices=[('$', 'دولار ($)'), ('SR', 'ريال سعودي (SR)'), ('£', 'جنيه إسترليني (£)')], default='SR', max_length=3, verbose_name='العملة'),
        ),
        migrations.AlterField(
            model_name='car',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='سعر التكلفة'),
        ),
        migrations.AlterField(
            model_name='car',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='سعر البيع'),
        ),
    ]
