# Generated by Django 6.0.2 on 2026-02-28 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_car_image_alter_car_id_alter_customer_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان المصروف')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ')),
                ('expense_type', models.CharField(choices=[('rent', 'إيجار'), ('utility', 'كهرباء ومياه'), ('salary', 'رواتب'), ('maintenance', 'صيانة سيارات'), ('other', 'أخرى')], max_length=20, verbose_name='نوع المصروف')),
                ('date', models.DateField(auto_now_add=True, verbose_name='التاريخ')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات إضافية')),
            ],
        ),
    ]
