# Generated by Django 6.0.2 on 2026-02-28 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='المبلغ المدفوع'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sale_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
