# Generated by Django 6.0.2 on 2026-03-01 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
