# Generated by Django 5.2.4 on 2026-03-02 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='contract_image',
            field=models.ImageField(blank=True, null=True, upload_to='car_docs/', verbose_name='صورة العقد/الأوراق'),
        ),
    ]
