# Generated by Django 5.2.4 on 2026-03-02 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_car_contract_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='DebtPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(max_length=30, unique=True, verbose_name='رقم السند')),
                ('payment_date', models.DateField(verbose_name='تاريخ السداد')),
                ('paid_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='المبلغ المسدد')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='sales.sale', verbose_name='عملية البيع')),
            ],
            options={
                'ordering': ['-payment_date', '-id'],
            },
        ),
    ]
