# Generated by Django 5.2.4 on 2026-03-02 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_debtpayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_type', models.CharField(choices=[('receipt', 'سند قبض'), ('payment', 'سند دفع'), ('operating', 'مصروفات تشغيلية'), ('settlement', 'سند تسديد')], max_length=20, verbose_name='نوع السند')),
                ('voucher_number', models.CharField(max_length=30, unique=True, verbose_name='رقم السند')),
                ('voucher_date', models.DateField(verbose_name='تاريخ السند')),
                ('person_name', models.CharField(max_length=150, verbose_name='الاسم')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='المبلغ')),
                ('currency', models.CharField(choices=[('$', 'دولار ($)'), ('SR', 'ريال سعودي (SR)'), ('£', 'جنيه إسترليني (£)')], default='SR', max_length=3, verbose_name='العملة')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='البيان')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-voucher_date', '-created_at'],
            },
        ),
    ]
