# Generated by Django 5.2.4 on 2026-03-03 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0017_normalize_operation_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='sales.car', verbose_name='السيارة المرتبطة'),
        ),
        migrations.AddField(
            model_name='sale',
            name='sale_contract_image',
            field=models.ImageField(blank=True, null=True, upload_to='sale_contracts/', verbose_name='صورة عقد البيع الموقّع'),
        ),
    ]
