# Generated by Django 5.2.4 on 2026-03-03 18:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0018_expense_car_sale_sale_contract_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterfaceAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_access_dashboard', models.BooleanField(default=True, verbose_name='لوحة التحكم')),
                ('can_access_cars', models.BooleanField(default=True, verbose_name='المعرض')),
                ('can_access_reports', models.BooleanField(default=True, verbose_name='التقارير')),
                ('can_access_debts', models.BooleanField(default=True, verbose_name='الديون')),
                ('can_access_timeline', models.BooleanField(default=True, verbose_name='الجدول الزمني')),
                ('can_access_system_users', models.BooleanField(default=True, verbose_name='حسابات المستخدمين')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='interface_access', to=settings.AUTH_USER_MODEL, verbose_name='الحساب')),
            ],
            options={
                'verbose_name': 'صلاحيات واجهات المستخدم',
                'verbose_name_plural': 'صلاحيات واجهات المستخدمين',
            },
        ),
    ]
