# Generated by Django 5.2.4 on 2026-03-03 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0019_interfaceaccess'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformTenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='اسم المعرض')),
                ('tenant_id', models.SlugField(unique=True, verbose_name='معرف المعرض')),
                ('access_key_hash', models.CharField(max_length=128, verbose_name='تجزئة كلمة مرور المعرض')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'معرض',
                'verbose_name_plural': 'المعارض',
            },
        ),
    ]
