# Generated by Django 5.2.4 on 2026-03-04 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0020_platformtenant'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.SlugField(blank=True, verbose_name='معرف المعرض')),
                ('actor_username', models.CharField(blank=True, max_length=150, verbose_name='اسم الحساب المنفذ')),
                ('event_type', models.CharField(choices=[('tenant_login', 'دخول معرض'), ('tenant_logout', 'خروج معرض'), ('platform_login', 'دخول منصة فوقية'), ('platform_switch', 'تحويل معرض فني'), ('platform_exit_switch', 'إنهاء التحويل الفني'), ('tenant_backup', 'نسخة احتياطية معرض'), ('tenant_restore', 'استعادة معرض'), ('tenant_migrate', 'هجرة معرض')], max_length=40, verbose_name='نوع الحدث')),
                ('data_size_bytes', models.BigIntegerField(default=0, verbose_name='حجم البيانات بالبايت')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت الحدث')),
            ],
            options={
                'verbose_name': 'سجل منصة عام',
                'verbose_name_plural': 'سجل المنصة العام',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='platformtenant',
            name='max_cars',
            field=models.PositiveIntegerField(default=500, verbose_name='الحد الأقصى للسيارات'),
        ),
        migrations.AddField(
            model_name='platformtenant',
            name='max_storage_mb',
            field=models.PositiveIntegerField(default=2048, verbose_name='الحد الأقصى للمساحة (MB)'),
        ),
        migrations.AddField(
            model_name='platformtenant',
            name='max_users',
            field=models.PositiveIntegerField(default=25, verbose_name='الحد الأقصى للمستخدمين'),
        ),
        migrations.CreateModel(
            name='TenantBackupRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backup_file', models.CharField(max_length=260, verbose_name='مسار ملف النسخة')),
                ('file_size_bytes', models.BigIntegerField(default=0, verbose_name='حجم الملف')),
                ('created_by', models.CharField(blank=True, max_length=150, verbose_name='المنفذ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backup_records', to='sales.platformtenant', verbose_name='المعرض')),
            ],
            options={
                'verbose_name': 'نسخة احتياطية معرض',
                'verbose_name_plural': 'النسخ الاحتياطية للمعارض',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TenantMigrationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('success', 'نجاح'), ('failed', 'فشل')], max_length=20, verbose_name='الحالة')),
                ('duration_ms', models.PositiveIntegerField(default=0, verbose_name='المدة بالميلي ثانية')),
                ('details', models.CharField(blank=True, max_length=255, verbose_name='تفاصيل')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='migration_records', to='sales.platformtenant', verbose_name='المعرض')),
            ],
            options={
                'verbose_name': 'سجل هجرة معرض',
                'verbose_name_plural': 'سجلات هجرة المعارض',
                'ordering': ['-created_at'],
            },
        ),
    ]
