# Generated by Django 5.2.4 on 2026-03-04 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0021_globalauditlog_platformtenant_max_cars_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformtenant',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف'),
        ),
        migrations.AddField(
            model_name='platformtenant',
            name='deleted_by',
            field=models.CharField(blank=True, max_length=150, verbose_name='تم الحذف بواسطة'),
        ),
        migrations.AddField(
            model_name='platformtenant',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='محذوف ناعمًا'),
        ),
        migrations.AlterField(
            model_name='globalauditlog',
            name='event_type',
            field=models.CharField(choices=[('tenant_login', 'دخول معرض'), ('tenant_logout', 'خروج معرض'), ('platform_login', 'دخول منصة فوقية'), ('platform_switch', 'تحويل معرض فني'), ('platform_exit_switch', 'إنهاء التحويل الفني'), ('tenant_backup', 'نسخة احتياطية معرض'), ('tenant_restore', 'استعادة معرض'), ('tenant_soft_delete', 'حذف ناعم لمعرض'), ('tenant_restore_soft_deleted', 'إعادة تفعيل معرض محذوف ناعمًا'), ('tenant_migrate', 'هجرة معرض')], max_length=40, verbose_name='نوع الحدث'),
        ),
    ]
