# Generated by Django 6.0.2 on 2026-03-05 22:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0022_platformtenant_deleted_at_platformtenant_deleted_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='financevoucher',
            name='credit_account',
            field=models.CharField(blank=True, choices=[('none', 'غير محدد'), ('operating_expenses', 'المصروفات التشغيلية'), ('maintenance_sold_cars', 'مصروفات صيانة السيارات المباعة'), ('cash_box', 'الصندوق'), ('bank', 'البنك')], default='none', max_length=40, verbose_name='الحساب الدائن'),
        ),
        migrations.AddField(
            model_name='financevoucher',
            name='debit_account',
            field=models.CharField(blank=True, choices=[('none', 'غير محدد'), ('operating_expenses', 'المصروفات التشغيلية'), ('maintenance_sold_cars', 'مصروفات صيانة السيارات المباعة'), ('cash_box', 'الصندوق'), ('bank', 'البنك')], default='none', max_length=40, verbose_name='الحساب المدين'),
        ),
        migrations.AddField(
            model_name='interfaceaccess',
            name='can_add_maintenance_expenses',
            field=models.BooleanField(default=False, verbose_name='إضافة مصروفات صيانة'),
        ),
        migrations.AlterField(
            model_name='financevoucher',
            name='voucher_type',
            field=models.CharField(choices=[('receipt', 'سند قبض'), ('payment', 'سند دفع'), ('operating', 'مصروفات تشغيلية'), ('settlement', 'سند تسديد'), ('maintenance', 'قيد صيانة سيارات')], max_length=20, verbose_name='نوع السند'),
        ),
        migrations.CreateModel(
            name='CarMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='مبلغ الصيانة')),
                ('maintenance_type', models.CharField(choices=[('mechanical', 'ميكانيكا'), ('bodywork', 'سمكرة'), ('polish', 'تلميع')], max_length=20, verbose_name='نوع الصيانة')),
                ('operation_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='تاريخ العملية')),
                ('supplier_workshop', models.CharField(max_length=150, verbose_name='المورد/الورشة')),
                ('payment_method', models.CharField(choices=[('cash', 'الصندوق'), ('bank', 'البنك')], default='cash', max_length=10, verbose_name='طريقة الدفع')),
                ('invoice_image', models.ImageField(upload_to='maintenance_invoices/', verbose_name='صورة الفاتورة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='الموظف الذي أضاف المصروف')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='sales.car', verbose_name='السيارة')),
                ('journal_voucher', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_record', to='sales.financevoucher', verbose_name='القيد المحاسبي')),
            ],
            options={
                'verbose_name': 'مصروف صيانة سيارة',
                'verbose_name_plural': 'مصروفات صيانة السيارات',
                'ordering': ['-operation_date', '-id'],
            },
        ),
    ]
