# Generated by Django 5.2.4 on 2026-03-06 01:38

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0023_financevoucher_credit_account_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='insurance_expiry',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ انتهاء التأمين'),
        ),
        migrations.AddField(
            model_name='car',
            name='registration_expiry',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ انتهاء الاستمارة'),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.SlugField(blank=True, verbose_name='معرف المعرض')),
                ('action', models.CharField(max_length=30, verbose_name='الإجراء')),
                ('target_model', models.CharField(max_length=80, verbose_name='اسم النموذج')),
                ('target_pk', models.CharField(blank=True, max_length=64, verbose_name='معرف السجل')),
                ('before_data', models.JSONField(blank=True, null=True, verbose_name='القيم السابقة')),
                ('after_data', models.JSONField(blank=True, null=True, verbose_name='القيم الجديدة')),
                ('ip_address', models.CharField(blank=True, max_length=64, verbose_name='عنوان IP')),
                ('request_path', models.CharField(blank=True, max_length=255, verbose_name='المسار')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='وقت العملية')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='الحساب')),
            ],
            options={
                'verbose_name': 'سجل تدقيق',
                'verbose_name_plural': 'سجل التدقيق',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='CarDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('registration', 'الاستمارة'), ('inspection', 'الفحص'), ('sale_contract', 'المبايعة')], max_length=30, verbose_name='نوع المستند')),
                ('file', models.FileField(upload_to='car_documents/%Y/%m/', verbose_name='ملف المستند')),
                ('upload_date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الرفع')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='sales.car', verbose_name='السيارة')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='تم الرفع بواسطة')),
            ],
            options={
                'verbose_name': 'مستند سيارة',
                'verbose_name_plural': 'مستندات السيارات',
                'ordering': ['-upload_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='GeneralExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='العنوان')),
                ('category', models.CharField(choices=[('rent', 'إيجار'), ('salary', 'رواتب'), ('bills', 'فواتير'), ('other', 'أخرى')], max_length=20, verbose_name='التصنيف')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='المبلغ')),
                ('currency', models.CharField(choices=[('$', 'دولار ($)'), ('SR', 'ريال سعودي (SR)'), ('£', 'جنيه إسترليني (£)')], default='SR', max_length=3, verbose_name='العملة')),
                ('expense_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='التاريخ')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='تمت الإضافة بواسطة')),
            ],
            options={
                'verbose_name': 'مصروف عام',
                'verbose_name_plural': 'المصروفات العامة',
                'ordering': ['-expense_date', '-id'],
            },
        ),
    ]
