# Generated by Django 6.0.2 on 2026-03-06 23:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0024_car_insurance_expiry_car_registration_expiry_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyClosing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('closing_date', models.DateField(unique=True, verbose_name='تاريخ اليومية المغلقة')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='ملاحظات الإغلاق')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت الإغلاق')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_closings', to=settings.AUTH_USER_MODEL, verbose_name='تم الإغلاق بواسطة')),
            ],
            options={
                'verbose_name': 'إغلاق يومية',
                'verbose_name_plural': 'إغلاقات اليومية',
                'ordering': ['-closing_date', '-created_at'],
            },
        ),
    ]
