# Generated by Django 6.0.2 on 2026-03-06 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0025_dailyclosing'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='debt_due_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ استحقاق المديونية'),
        ),
    ]
