# Generated by Django 6.0.2 on 2026-03-06 23:47

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0026_sale_debt_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='commission_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='العمولة'),
        ),
        migrations.AddField(
            model_name='car',
            name='customs_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='رسوم الجمارك'),
        ),
        migrations.AddField(
            model_name='car',
            name='transport_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='تكاليف النقل'),
        ),
    ]
