# Generated by Django 6.0.2 on 2026-03-07 00:14

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0027_car_commission_cost_car_customs_cost_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='financevoucher',
            name='linked_car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_vouchers', to='sales.car', verbose_name='مركز التكلفة (السيارة)'),
        ),
        migrations.AddField(
            model_name='financevoucher',
            name='supporting_document',
            field=models.FileField(blank=True, null=True, upload_to='voucher_docs/%Y/%m/', verbose_name='المستند المرفق'),
        ),
        migrations.AlterField(
            model_name='globalauditlog',
            name='event_type',
            field=models.CharField(choices=[('tenant_login', 'دخول معرض'), ('tenant_logout', 'خروج معرض'), ('platform_login', 'دخول منصة فوقية'), ('platform_switch', 'تحويل معرض فني'), ('platform_exit_switch', 'إنهاء التحويل الفني'), ('fiscal_period_close', 'إغلاق فترة مالية'), ('fiscal_unlock_request', 'طلب فك إغلاق مالي'), ('fiscal_unlock_approved', 'اعتماد فك الإغلاق المالي'), ('fiscal_unlock_rejected', 'رفض فك الإغلاق المالي'), ('tenant_backup', 'نسخة احتياطية معرض'), ('tenant_restore', 'استعادة معرض'), ('tenant_soft_delete', 'حذف ناعم لمعرض'), ('tenant_restore_soft_deleted', 'إعادة تفعيل معرض محذوف ناعمًا'), ('tenant_migrate', 'هجرة معرض')], max_length=40, verbose_name='نوع الحدث'),
        ),
        migrations.CreateModel(
            name='FinancialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='رمز الحساب')),
                ('name', models.CharField(max_length=160, verbose_name='اسم الحساب')),
                ('account_type', models.CharField(choices=[('asset', 'أصول'), ('liability', 'خصوم'), ('equity', 'حقوق ملكية'), ('revenue', 'إيرادات'), ('expense', 'مصروفات')], max_length=20, verbose_name='نوع الحساب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('is_system', models.BooleanField(default=False, verbose_name='حساب نظام')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='sales.financialaccount', verbose_name='الحساب الأب')),
            ],
            options={
                'verbose_name': 'حساب مالي',
                'verbose_name_plural': 'شجرة الحسابات',
                'ordering': ['code', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FinancialContainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='اسم الوعاء المالي')),
                ('container_type', models.CharField(choices=[('main_cash', 'خزينة رئيسية'), ('custody', 'عهدة موظف'), ('bank', 'حساب بنكي')], max_length=20, verbose_name='نوع الوعاء')),
                ('currency', models.CharField(choices=[('$', 'دولار ($)'), ('SR', 'ريال سعودي (SR)'), ('£', 'جنيه إسترليني (£)')], default='SR', max_length=3, verbose_name='العملة')),
                ('opening_balance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='الرصيد الافتتاحي')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('linked_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='financial_containers', to='sales.financialaccount', verbose_name='الحساب المرتبط')),
            ],
            options={
                'verbose_name': 'وعاء مالي',
                'verbose_name_plural': 'الأوعية المالية',
                'ordering': ['name', 'id'],
            },
        ),
        migrations.AddField(
            model_name='financevoucher',
            name='financial_container',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vouchers', to='sales.financialcontainer', verbose_name='الوعاء المالي'),
        ),
        migrations.CreateModel(
            name='FiscalPeriodClosing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('monthly', 'إغلاق شهري')], default='monthly', max_length=20, verbose_name='نوع الإغلاق')),
                ('period_start', models.DateField(verbose_name='بداية الفترة')),
                ('period_end', models.DateField(verbose_name='نهاية الفترة')),
                ('is_locked', models.BooleanField(default=True, verbose_name='الفترة مغلقة')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='ملاحظات الإغلاق')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fiscal_period_closings', to=settings.AUTH_USER_MODEL, verbose_name='تم الإغلاق بواسطة')),
            ],
            options={
                'verbose_name': 'إغلاق فترة مالية',
                'verbose_name_plural': 'إغلاقات الفترات المالية',
                'ordering': ['-period_end', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FiscalUnlockRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(verbose_name='مبرر طلب فك الإغلاق')),
                ('status', models.CharField(choices=[('pending', 'قيد المراجعة'), ('approved', 'مقبول'), ('rejected', 'مرفوض')], default='pending', max_length=20, verbose_name='الحالة')),
                ('review_notes', models.CharField(blank=True, max_length=255, verbose_name='ملاحظات المراجعة')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ المراجعة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlock_requests', to='sales.fiscalperiodclosing', verbose_name='الفترة المالية')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fiscal_unlock_requests', to=settings.AUTH_USER_MODEL, verbose_name='طالب فك الإغلاق')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fiscal_unlock_reviews', to=settings.AUTH_USER_MODEL, verbose_name='تمت المراجعة بواسطة')),
            ],
            options={
                'verbose_name': 'طلب فك إغلاق',
                'verbose_name_plural': 'طلبات فك الإغلاق',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_number', models.CharField(max_length=40, unique=True, verbose_name='رقم القيد')),
                ('entry_date', models.DateField(verbose_name='تاريخ القيد')),
                ('description', models.CharField(max_length=255, verbose_name='وصف القيد')),
                ('source_model', models.CharField(blank=True, max_length=80, verbose_name='مصدر القيد')),
                ('source_pk', models.CharField(blank=True, max_length=64, verbose_name='معرف المصدر')),
                ('source_reference', models.CharField(blank=True, max_length=80, verbose_name='مرجع المصدر')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries', to=settings.AUTH_USER_MODEL, verbose_name='تم الإنشاء بواسطة')),
            ],
            options={
                'verbose_name': 'قيد يومية',
                'verbose_name_plural': 'قيود اليومية',
                'ordering': ['-entry_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntryLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_description', models.CharField(blank=True, max_length=255, verbose_name='بيان السطر')),
                ('debit', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='مدين')),
                ('credit', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='دائن')),
                ('currency', models.CharField(choices=[('$', 'دولار ($)'), ('SR', 'ريال سعودي (SR)'), ('£', 'جنيه إسترليني (£)')], default='SR', max_length=3, verbose_name='العملة')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal_lines', to='sales.financialaccount', verbose_name='الحساب')),
                ('car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_lines', to='sales.car', verbose_name='مركز التكلفة (السيارة)')),
                ('container', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_lines', to='sales.financialcontainer', verbose_name='الوعاء المالي')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.journalentry', verbose_name='القيد')),
            ],
            options={
                'verbose_name': 'سطر قيد',
                'verbose_name_plural': 'سطور القيود',
                'ordering': ['entry_id', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='fiscalperiodclosing',
            constraint=models.UniqueConstraint(fields=('period_type', 'period_start', 'period_end'), name='uniq_fiscal_period_closing_window'),
        ),
    ]
