# Generated by Django 5.2.4 on 2026-03-07 00:51

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0028_financevoucher_linked_car_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_order', models.PositiveIntegerField(default=1, verbose_name='ترتيب القسط')),
                ('due_date', models.DateField(verbose_name='تاريخ الاستحقاق')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='قيمة القسط')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='المبلغ المسدد')),
                ('status', models.CharField(choices=[('pending', 'مستحق'), ('partial', 'مسدد جزئياً'), ('paid', 'مسدد')], default='pending', max_length=12, verbose_name='الحالة')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='ملاحظة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='sales.sale', verbose_name='عملية البيع')),
            ],
            options={
                'verbose_name': 'قسط بيع',
                'verbose_name_plural': 'أقساط البيع',
                'ordering': ['due_date', 'installment_order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('sale', 'installment_order'), name='uniq_sale_installment_order')],
            },
        ),
    ]
