# Generated by Django 5.2.4 on 2026-03-07 23:14

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0029_saleinstallment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6, unique=True, verbose_name='رمز العملة')),
                ('name', models.CharField(max_length=80, verbose_name='اسم العملة')),
                ('symbol', models.CharField(blank=True, max_length=8, verbose_name='الرمز')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشطة')),
            ],
            options={
                'verbose_name': 'عملة',
                'verbose_name_plural': 'العملات',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='المسمى الوظيفي')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='الوصف')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'دور وظيفي',
                'verbose_name_plural': 'الأدوار الوظيفية',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='اسم المورد')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='الهاتف')),
                ('tax_number', models.CharField(blank=True, max_length=60, verbose_name='الرقم الضريبي')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='العنوان')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'مورد',
                'verbose_name_plural': 'الموردون',
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TaxRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='اسم الضريبة')),
                ('rate_percent', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, verbose_name='نسبة الضريبة')),
                ('is_active', models.BooleanField(default=True, verbose_name='حالة التفعيل')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'ضريبة',
                'verbose_name_plural': 'الضرائب',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='auditlog',
            name='browser',
            field=models.CharField(blank=True, max_length=120, verbose_name='المتصفح'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='device_type',
            field=models.CharField(blank=True, max_length=80, verbose_name='نوع الجهاز'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='geo_location',
            field=models.CharField(blank=True, max_length=120, verbose_name='الموقع الجغرافي التقريبي'),
        ),
        migrations.CreateModel(
            name='CarEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='تاريخ التقييم')),
                ('market_value', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='القيمة السوقية')),
                ('evaluator_name', models.CharField(blank=True, max_length=150, verbose_name='المقيّم')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='sales.car', verbose_name='السيارة')),
            ],
            options={
                'verbose_name': 'تقييم سيارة',
                'verbose_name_plural': 'تقييمات السيارات',
                'ordering': ['-evaluation_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CarHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('purchase', 'شراء'), ('maintenance', 'صيانة'), ('transfer', 'نقل'), ('listed', 'عرض للبيع'), ('sold', 'بيع')], max_length=20, verbose_name='نوع الحدث')),
                ('event_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='تاريخ الحدث')),
                ('reference_type', models.CharField(blank=True, max_length=40, verbose_name='نوع المرجع')),
                ('reference_id', models.CharField(blank=True, max_length=64, verbose_name='معرف المرجع')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_items', to='sales.car', verbose_name='السيارة')),
            ],
            options={
                'verbose_name': 'سجل تاريخ السيارة',
                'verbose_name_plural': 'سجل تاريخ السيارات',
                'ordering': ['-event_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CarReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='تاريخ الحجز')),
                ('expiry_date', models.DateField(verbose_name='تاريخ انتهاء الحجز')),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='مبلغ العربون')),
                ('is_active', models.BooleanField(default=True, verbose_name='الحجز نشط')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='sales.car', verbose_name='السيارة')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='car_reservations', to='sales.customer', verbose_name='العميل')),
            ],
            options={
                'verbose_name': 'حجز سيارة',
                'verbose_name_plural': 'حجوزات السيارات',
                'ordering': ['-reservation_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CustomerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_debt', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='إجمالي الديون')),
                ('total_paid', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='إجمالي المدفوع')),
                ('current_balance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='الرصيد الحالي')),
                ('last_payment_date', models.DateField(blank=True, null=True, verbose_name='تاريخ آخر سداد')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account_summary', to='sales.customer', verbose_name='العميل')),
            ],
            options={
                'verbose_name': 'حساب عميل',
                'verbose_name_plural': 'حسابات العملاء',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='الاسم')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='الهاتف')),
                ('hire_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='تاريخ التعيين')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_profile', to=settings.AUTH_USER_MODEL, verbose_name='الحساب')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='sales.employeerole', verbose_name='الدور')),
            ],
            options={
                'verbose_name': 'موظف',
                'verbose_name_plural': 'الموظفون',
                'ordering': ['full_name', 'id'],
            },
        ),
        migrations.AddField(
            model_name='sale',
            name='sales_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='sales.employee', verbose_name='الموظف المسؤول'),
        ),
        migrations.CreateModel(
            name='EmployeeCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField(verbose_name='من تاريخ')),
                ('period_end', models.DateField(verbose_name='إلى تاريخ')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='قيمة العمولة')),
                ('is_paid', models.BooleanField(default=False, verbose_name='تم الصرف')),
                ('paid_at', models.DateField(blank=True, null=True, verbose_name='تاريخ الصرف')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='ملاحظات')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_periods', to='sales.employee', verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'عمولة موظف دورية',
                'verbose_name_plural': 'عمولات الموظفين الدورية',
                'ordering': ['-period_start', '-id'],
            },
        ),
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('purchase', 'شراء'), ('sale', 'بيع'), ('adjustment', 'تعديل'), ('maintenance', 'صيانة')], max_length=20, verbose_name='نوع الحركة')),
                ('transaction_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='التاريخ')),
                ('cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='التكلفة')),
                ('reference_type', models.CharField(blank=True, max_length=40, verbose_name='نوع المرجع')),
                ('reference_id', models.CharField(blank=True, max_length=64, verbose_name='المرجع المرتبط بالعملية')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_transactions', to='sales.car', verbose_name='السيارة')),
            ],
            options={
                'verbose_name': 'حركة مخزون',
                'verbose_name_plural': 'حركات المخزون',
                'ordering': ['transaction_date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=40, unique=True, verbose_name='رقم الفاتورة')),
                ('invoice_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='تاريخ الفاتورة')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الاستحقاق')),
                ('currency', models.CharField(choices=[('$', 'دولار ($)'), ('SR', 'ريال سعودي (SR)'), ('£', 'جنيه إسترليني (£)')], default='SR', max_length=3, verbose_name='العملة')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='الإجمالي قبل الضريبة')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='قيمة الضريبة')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='الإجمالي النهائي')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('issued', 'مُصدرة'), ('paid', 'مسددة'), ('cancelled', 'ملغاة')], default='draft', max_length=12, verbose_name='الحالة')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='sales.customer', verbose_name='العميل')),
                ('sale', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice', to='sales.sale', verbose_name='عملية البيع')),
                ('tax_rate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='sales.taxrate', verbose_name='الضريبة')),
            ],
            options={
                'verbose_name': 'فاتورة',
                'verbose_name_plural': 'الفواتير',
                'ordering': ['-invoice_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_type', models.CharField(choices=[('car', 'سيارة'), ('transport', 'رسوم نقل'), ('commission', 'عمولات'), ('service', 'خدمات إضافية'), ('registration', 'مصاريف تسجيل'), ('other', 'أخرى')], default='other', max_length=20, verbose_name='نوع البند')),
                ('description', models.CharField(max_length=255, verbose_name='الوصف')),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=10, verbose_name='الكمية')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='سعر الوحدة')),
                ('line_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='إجمالي السطر')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_lines', to='sales.car', verbose_name='السيارة')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.invoice', verbose_name='الفاتورة')),
            ],
            options={
                'verbose_name': 'بند فاتورة',
                'verbose_name_plural': 'بنود الفواتير',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SalesCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, verbose_name='نسبة العمولة')),
                ('commission_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='قيمة العمولة')),
                ('payout_status', models.CharField(choices=[('pending', 'قيد المراجعة'), ('approved', 'معتمدة'), ('paid', 'مصروفة')], default='pending', max_length=12, verbose_name='حالة الصرف')),
                ('paid_at', models.DateField(blank=True, null=True, verbose_name='تاريخ الصرف')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_commissions', to='sales.employee', verbose_name='الموظف')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_commissions', to='sales.sale', verbose_name='عملية البيع')),
            ],
            options={
                'verbose_name': 'عمولة بيع',
                'verbose_name_plural': 'عمولات المبيعات',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SupplierInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=40, unique=True, verbose_name='رقم الفاتورة')),
                ('invoice_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='تاريخ الفاتورة')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الاستحقاق')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='إجمالي الفاتورة')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='المبلغ المسدد')),
                ('status', models.CharField(choices=[('pending', 'مستحق'), ('partial', 'مسدد جزئياً'), ('paid', 'مسدد بالكامل')], default='pending', max_length=12, verbose_name='الحالة')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_invoices', to='sales.car', verbose_name='السيارة')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='sales.supplier', verbose_name='المورد')),
            ],
            options={
                'verbose_name': 'فاتورة مورد',
                'verbose_name_plural': 'فواتير الموردين',
                'ordering': ['-invoice_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SupplierPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_number', models.CharField(max_length=40, unique=True, verbose_name='رقم الدفعة')),
                ('payment_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='تاريخ الدفع')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='المبلغ')),
                ('payment_method', models.CharField(choices=[('cash', 'نقدي'), ('bank', 'تحويل بنكي')], default='cash', max_length=10, verbose_name='طريقة الدفع')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='sales.supplierinvoice', verbose_name='الفاتورة')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='sales.supplier', verbose_name='المورد')),
            ],
            options={
                'verbose_name': 'دفعة مورد',
                'verbose_name_plural': 'دفعات الموردين',
                'ordering': ['-payment_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AccountLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField(verbose_name='التاريخ')),
                ('debit', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='قيمة المدين')),
                ('credit', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='قيمة الدائن')),
                ('balance_after', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='الرصيد بعد العملية')),
                ('reference_type', models.CharField(choices=[('sale', 'بيع'), ('voucher', 'سند'), ('maintenance', 'صيانة'), ('expense', 'مصروف'), ('other', 'أخرى')], default='other', max_length=20, verbose_name='نوع المرجع')),
                ('reference_id', models.CharField(blank=True, max_length=64, verbose_name='معرف العملية المرجعية')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='sales.financialaccount', verbose_name='الحساب المالي')),
                ('journal_line', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entry', to='sales.journalentryline', verbose_name='سطر القيد المرتبط')),
            ],
            options={
                'verbose_name': 'دفتر أستاذ عام',
                'verbose_name_plural': 'دفتر الأستاذ العام',
                'ordering': ['transaction_date', 'id'],
                'indexes': [models.Index(fields=['account', 'transaction_date', 'id'], name='sales_accou_account_b2c0b9_idx'), models.Index(fields=['reference_type', 'reference_id'], name='sales_accou_referen_265158_idx')],
            },
        ),
        migrations.CreateModel(
            name='CarLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('showroom_name', models.CharField(max_length=120, verbose_name='المعرض')),
                ('row_label', models.CharField(max_length=40, verbose_name='الصف')),
                ('spot_label', models.CharField(max_length=40, verbose_name='الموقع')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('car', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='sales.car', verbose_name='السيارة')),
            ],
            options={
                'verbose_name': 'موقع سيارة',
                'verbose_name_plural': 'مواقع السيارات',
                'ordering': ['showroom_name', 'row_label', 'spot_label'],
                'constraints': [models.UniqueConstraint(fields=('showroom_name', 'row_label', 'spot_label'), name='uniq_car_location_spot')],
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='تاريخ السعر')),
                ('rate', models.DecimalField(decimal_places=6, max_digits=18, verbose_name='سعر الصرف')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='source_rates', to='sales.currency', verbose_name='من عملة')),
                ('to_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='target_rates', to='sales.currency', verbose_name='إلى عملة')),
            ],
            options={
                'verbose_name': 'سعر صرف',
                'verbose_name_plural': 'أسعار الصرف',
                'ordering': ['-rate_date', 'from_currency__code', 'to_currency__code'],
                'constraints': [models.UniqueConstraint(fields=('from_currency', 'to_currency', 'rate_date'), name='uniq_exchange_rate_daily_pair')],
            },
        ),
    ]
