# Generated by Django 5.2.4 on 2026-03-27 00:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0030_currency_employeerole_supplier_taxrate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='debtpayment',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف'),
        ),
        migrations.AddField(
            model_name='debtpayment',
            name='deleted_by',
            field=models.CharField(blank=True, max_length=150, verbose_name='تم الحذف بواسطة'),
        ),
        migrations.AddField(
            model_name='debtpayment',
            name='deletion_note',
            field=models.CharField(blank=True, max_length=255, verbose_name='سبب الحذف'),
        ),
        migrations.AddField(
            model_name='debtpayment',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='محذوف ناعماً'),
        ),
        migrations.AddField(
            model_name='financevoucher',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف'),
        ),
        migrations.AddField(
            model_name='financevoucher',
            name='deleted_by',
            field=models.CharField(blank=True, max_length=150, verbose_name='تم الحذف بواسطة'),
        ),
        migrations.AddField(
            model_name='financevoucher',
            name='deletion_note',
            field=models.CharField(blank=True, max_length=255, verbose_name='سبب الحذف'),
        ),
        migrations.AddField(
            model_name='financevoucher',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='محذوف ناعماً'),
        ),
        migrations.AddField(
            model_name='financevoucher',
            name='reversed_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversal_entries', to='sales.financevoucher', verbose_name='قيد عكسي لسند'),
        ),
    ]
