# Generated by Django 6.0.3 on 2026-03-29 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0034_alter_userthemepreference_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalauditlog',
            name='event_type',
            field=models.CharField(choices=[('tenant_login', 'دخول معرض'), ('tenant_logout', 'خروج معرض'), ('platform_login', 'دخول منصة فوقية'), ('platform_login_failed', 'فشل دخول منصة فوقية'), ('platform_switch', 'تحويل معرض فني'), ('platform_exit_switch', 'إنهاء التحويل الفني'), ('fiscal_period_close', 'إغلاق فترة مالية'), ('fiscal_unlock_request', 'طلب فك إغلاق مالي'), ('fiscal_unlock_approved', 'اعتماد فك الإغلاق المالي'), ('fiscal_unlock_rejected', 'رفض فك الإغلاق المالي'), ('tenant_backup', 'نسخة احتياطية معرض'), ('tenant_restore', 'استعادة معرض'), ('tenant_soft_delete', 'حذف ناعم لمعرض'), ('tenant_restore_soft_deleted', 'إعادة تفعيل معرض محذوف ناعمًا'), ('tenant_migrate', 'هجرة معرض')], max_length=40, verbose_name='نوع الحدث'),
        ),
    ]
