# Generated by Django 6.0.3 on 2026-03-29 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0035_alter_globalauditlog_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='currency',
            field=models.CharField(choices=[('$', 'دولار ($)'), ('SR', 'ريال سعودي (SR)'), ('YER', 'ريال يمني (YER)'), ('£', 'جنيه إسترليني (£)')], default='SR', max_length=3, verbose_name='العملة'),
        ),
        migrations.AlterField(
            model_name='financevoucher',
            name='currency',
            field=models.CharField(choices=[('$', 'دولار ($)'), ('SR', 'ريال سعودي (SR)'), ('YER', 'ريال يمني (YER)'), ('£', 'جنيه إسترليني (£)')], default='SR', max_length=3, verbose_name='العملة'),
        ),
        migrations.AlterField(
            model_name='financialcontainer',
            name='currency',
            field=models.CharField(choices=[('$', 'دولار ($)'), ('SR', 'ريال سعودي (SR)'), ('YER', 'ريال يمني (YER)'), ('£', 'جنيه إسترليني (£)')], default='SR', max_length=3, verbose_name='العملة'),
        ),
        migrations.AlterField(
            model_name='generalexpense',
            name='currency',
            field=models.CharField(choices=[('$', 'دولار ($)'), ('SR', 'ريال سعودي (SR)'), ('YER', 'ريال يمني (YER)'), ('£', 'جنيه إسترليني (£)')], default='SR', max_length=3, verbose_name='العملة'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='currency',
            field=models.CharField(choices=[('$', 'دولار ($)'), ('SR', 'ريال سعودي (SR)'), ('YER', 'ريال يمني (YER)'), ('£', 'جنيه إسترليني (£)')], default='SR', max_length=3, verbose_name='العملة'),
        ),
        migrations.AlterField(
            model_name='journalentryline',
            name='currency',
            field=models.CharField(choices=[('$', 'دولار ($)'), ('SR', 'ريال سعودي (SR)'), ('YER', 'ريال يمني (YER)'), ('£', 'جنيه إسترليني (£)')], default='SR', max_length=3, verbose_name='العملة'),
        ),
    ]
