# Generated by Django 6.0.3 on 2026-03-31 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0036_add_yer_yemeni_rial_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='currency',
            field=models.CharField(choices=[('$', 'دولار ($)'), ('SR', 'ريال سعودي (SR)'), ('YER', 'ريال يمني (YER)'), ('KRW', 'وون كوري (KRW)'), ('CNY', 'يوان صيني (CNY)'), ('EUR', 'يورو (EUR)'), ('£', 'جنيه إسترليني (£)')], default='SR', max_length=3, verbose_name='العملة'),
        ),
        migrations.AlterField(
            model_name='financevoucher',
            name='currency',
            field=models.CharField(choices=[('$', 'دولار ($)'), ('SR', 'ريال سعودي (SR)'), ('YER', 'ريال يمني (YER)'), ('KRW', 'وون كوري (KRW)'), ('CNY', 'يوان صيني (CNY)'), ('EUR', 'يورو (EUR)'), ('£', 'جنيه إسترليني (£)')], default='SR', max_length=3, verbose_name='العملة'),
        ),
        migrations.AlterField(
            model_name='financialcontainer',
            name='currency',
            field=models.CharField(choices=[('$', 'دولار ($)'), ('SR', 'ريال سعودي (SR)'), ('YER', 'ريال يمني (YER)'), ('KRW', 'وون كوري (KRW)'), ('CNY', 'يوان صيني (CNY)'), ('EUR', 'يورو (EUR)'), ('£', 'جنيه إسترليني (£)')], default='SR', max_length=3, verbose_name='العملة'),
        ),
        migrations.AlterField(
            model_name='generalexpense',
            name='currency',
            field=models.CharField(choices=[('$', 'دولار ($)'), ('SR', 'ريال سعودي (SR)'), ('YER', 'ريال يمني (YER)'), ('KRW', 'وون كوري (KRW)'), ('CNY', 'يوان صيني (CNY)'), ('EUR', 'يورو (EUR)'), ('£', 'جنيه إسترليني (£)')], default='SR', max_length=3, verbose_name='العملة'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='currency',
            field=models.CharField(choices=[('$', 'دولار ($)'), ('SR', 'ريال سعودي (SR)'), ('YER', 'ريال يمني (YER)'), ('KRW', 'وون كوري (KRW)'), ('CNY', 'يوان صيني (CNY)'), ('EUR', 'يورو (EUR)'), ('£', 'جنيه إسترليني (£)')], default='SR', max_length=3, verbose_name='العملة'),
        ),
        migrations.AlterField(
            model_name='journalentryline',
            name='currency',
            field=models.CharField(choices=[('$', 'دولار ($)'), ('SR', 'ريال سعودي (SR)'), ('YER', 'ريال يمني (YER)'), ('KRW', 'وون كوري (KRW)'), ('CNY', 'يوان صيني (CNY)'), ('EUR', 'يورو (EUR)'), ('£', 'جنيه إسترليني (£)')], default='SR', max_length=3, verbose_name='العملة'),
        ),
    ]
